services:
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "postgres-db-project"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - dbproject:/data/postgres-project
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    dbproject:
      external: true